import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Sparkles,CalendarDays,ShieldCheck,Star,ArrowRight,Check,Menu,X,Clock,MapPin,Phone,Instagram}from'lucide-react';import'./styles.css';
const treatments=[['Wrinkle Relaxers','Smooth expression lines while keeping your look natural.','01'],['Signature Facials','Personalized treatments for brighter, healthier-looking skin.','02'],['Laser Hair Removal','A convenient path to smoother skin with less daily maintenance.','03'],['Body Contouring','Non-surgical treatments designed around your body goals.','04']];
const faqs=[['Do I need a consultation first?','Yes. Your consultation helps us understand your goals and recommend an appropriate treatment plan.'],['How long does an appointment take?','It depends on the service. Many appointments fit comfortably into a lunch break, while others require more time.'],['When will I see results?','Timing varies by treatment and by person. Your provider will explain realistic expectations during your consultation.'],['Can I book online?','Yes. Use any Book Consultation button to request your preferred date and time.']];
function App(){const[menu,setMenu]=useState(false);const[modal,setModal]=useState(false);const[done,setDone]=useState(false);const open=()=>{setModal(true);setMenu(false)};return <><header><a className="brand" href="#top">LUMÉRA <span>MED SPA</span></a><nav className={menu?'open':''}><a href="#treatments" onClick={()=>setMenu(false)}>Treatments</a><a href="#results" onClick={()=>setMenu(false)}>Results</a><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#faq" onClick={()=>setMenu(false)}>FAQ</a><button className="btn small" onClick={open}>Book Consultation</button></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main id="top"><section className="hero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> DALLAS, TEXAS</div><h1>Look refreshed.<br/><em>Feel like yourself.</em></h1><p>Personalized aesthetic treatments with a thoughtful, natural approach—designed around your goals, comfort and confidence.</p><div className="actions"><button className="btn" onClick={open}>Book Your Consultation <ArrowRight size={18}/></button><a className="textLink" href="#treatments">Explore treatments</a></div><div className="trust"><span><Star size={16} fill="currentColor"/> 4.9 client rating</span><span><ShieldCheck size={17}/> Personalized care</span></div></div><div className="heroVisual"><div className="arch"><div className="face"></div></div><div className="floating"><span>NEW CLIENTS</span><b>Complimentary<br/>Consultation</b></div></div></section>
<section className="strip"><span>Natural-looking results</span><i>•</i><span>Personalized plans</span><i>•</i><span>Modern treatments</span><i>•</i><span>Easy online booking</span></section>
<section className="section" id="treatments"><div className="sectionHead"><div><span className="kicker">OUR TREATMENTS</span><h2>Subtle enhancements.<br/>Confident results.</h2></div><p>Every treatment begins with your goals. We create a plan that feels personal, considered and never one-size-fits-all.</p></div><div className="cards">{treatments.map(([n,d,num])=><article className="card" key={n}><span className="num">{num}</span><div className="treatmentIcon">✦</div><h3>{n}</h3><p>{d}</p><button onClick={open}>Book consultation <ArrowRight size={15}/></button></article>)}</div></section>
<section className="split" id="about"><div className="photoBlock"><div className="room"></div><div className="badge"><b>Thoughtful care</b><span>from consultation to follow-up</span></div></div><div className="splitCopy"><span className="kicker">THE LUMÉRA DIFFERENCE</span><h2>Beauty should still<br/><em>look like you.</em></h2><p>We believe the best aesthetic care starts by listening. Your provider takes time to understand what you want, explain your options and create a treatment plan without pressure.</p><ul><li><Check/>Experienced aesthetic providers</li><li><Check/>Personalized treatment plans</li><li><Check/>Comfortable, modern environment</li><li><Check/>Simple booking and follow-up</li></ul><button className="btn" onClick={open}>Start With a Consultation</button></div></section>
<section className="results section" id="results"><span className="kicker">CLIENT EXPERIENCE</span><h2>Care people come back for.</h2><div className="reviews">{[['“I wanted to look refreshed, not different. They listened and the whole experience felt incredibly personal.”','MAYA R.'],['“From booking to follow-up, everything was easy. I never felt rushed or pushed into a treatment.”','JESSICA T.'],['“The consultation gave me confidence because I finally understood which treatments actually made sense for me.”','AMANDA L.']].map(([q,n])=><blockquote key={n}><div className="stars">★★★★★</div><p>{q}</p><footer>{n} <span>Verified Client</span></footer></blockquote>)}</div></section>
<section className="offer"><div><span className="kicker light">NEW CLIENT OFFER</span><h2>Your first step is simple.</h2><p>Meet with a provider, talk through your goals and get a personalized recommendation—without pressure.</p></div><div className="offerAction"><span>Complimentary</span><strong>Consultation</strong><button className="btn lightBtn" onClick={open}>Reserve Your Visit <CalendarDays size={18}/></button></div></section>
<section className="section faq" id="faq"><div><span className="kicker">QUESTIONS, ANSWERED</span><h2>Before your visit.</h2><p>Still have a question? Our team will be happy to help before you book.</p></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="final"><Sparkles/><h2>Ready to feel like<br/><em>your best self?</em></h2><p>Your personalized treatment plan starts with a conversation.</p><button className="btn" onClick={open}>Book Your Consultation <ArrowRight size={18}/></button></section></main>
<footer><div className="brand footbrand">LUMÉRA <span>MED SPA</span></div><div><b>Visit</b><span><MapPin size={14}/> Dallas, Texas</span><span><Clock size={14}/> Mon–Sat · By appointment</span></div><div><b>Connect</b><span><Phone size={14}/> (214) 555-0148</span><span><Instagram size={14}/> @lumeramedspa</span></div><small>Demo website for portfolio presentation. Luméra Med Spa is a fictional brand.</small></footer>
{modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><div className="modal"><button className="close" onClick={()=>setModal(false)}><X/></button>{done?<div className="success"><div>✓</div><h2>Request received.</h2><p>In a live GHL setup, this is where the lead enters the CRM and the automated follow-up begins.</p><button className="btn" onClick={()=>{setModal(false);setDone(false)}}>Done</button></div>:<><span className="kicker">BOOK A CONSULTATION</span><h2>Let's find a time for you.</h2><p className="muted">Demo booking form — this will later connect directly to GoHighLevel.</p><form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>Full name<input required placeholder="Your name"/></label><label>Phone<input required type="tel" placeholder="(555) 000-0000"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>I'm interested in<select required defaultValue=""><option value="" disabled>Select a treatment</option>{treatments.map(x=><option key={x[0]}>{x[0]}</option>)}</select></label><div className="two"><label>Preferred date<input required type="date"/></label><label>Preferred time<select><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label></div><button className="btn full">Request Consultation <ArrowRight size={17}/></button></form></>}</div></div>}</>}
createRoot(document.getElementById('root')).render(<App/>);
